### ISSUE TITLE
Console Spam when pinging server in Multiplayer list with errors.

### ISSUE THREAD

**Issue by X-Niter** [AnvilPowered/Catalyst#39] opened 2020-08-31 05:54 UTC
**Describe the bug**
A clear description of the bug:

When I ping my server in the multiplayer page of minecraft, I am sent a very large Error that references my MOTD.

**To Reproduce**

Simply set up the database info as needed, Let everything be default or even having everything to false or Disabled.

**Expected behavior**

I imagine the spamming of Error was not part of the plan, though this is still in dev so I'm not too worried about it.

**Screenshots**

Even better, Here is the link to the Error, of course, shorten down to just the error and not the duplicates.
https://hastebin.com/naruzidage.php

**Desktop (please complete the following information):**
 - Velocity Version: velocity-proxy-1.1.0
 - Catalyst Version: Catalyst-Velocity-0.2.1

 - Additional Plugins installed on velocity: 

Anvil-Velocity-0.2.1
LuckPerms-Velocity-5.1.93

**Additional context**

**Comment by alexstaeding** [comment] 2020-08-31 10:49
The problem is caused by a breaking change in kyori adventure. Will push a fix to anvil shortly

**Comment by X-Niter** [comment] 2020-08-31 17:12
Thank you for Alex, 
I can close this if you like or if you wish to keep it open?

**Comment by alexstaeding** [comment] 2020-08-31 21:07
Resolved by https://github.com/KyoriPowered/adventure/commit/de20e4707cd5e78f76ab9ce74b34b02b4b519fd5

**Closed by alexstaeding** 2020-08-31 21:07 UTC
Labels: bug
